# Generated by Django 3.2.8 on 2021-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pkmlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('german_name', models.CharField(max_length=200)),
                ('japanese_name', models.CharField(max_length=200)),
                ('generation', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('type_number', models.IntegerField()),
                ('type_1', models.CharField(blank=True, max_length=200, null=True)),
                ('type_2', models.CharField(blank=True, max_length=200, null=True)),
                ('height_m', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=2)),
                ('abilities_number', models.IntegerField()),
                ('ability_1', models.CharField(blank=True, max_length=200, null=True)),
                ('ability_2', models.CharField(blank=True, max_length=200, null=True)),
                ('ability_hidden', models.CharField(max_length=250)),
                ('total_points', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('catch_rate', models.IntegerField()),
                ('base_friendship', models.IntegerField()),
                ('base_experience', models.IntegerField()),
                ('growth_rate', models.CharField(max_length=200)),
                ('egg_type_number', models.IntegerField()),
                ('egg_type_1', models.CharField(blank=True, max_length=200, null=True)),
                ('egg_type_2', models.CharField(blank=True, max_length=200, null=True)),
                ('percentage_male', models.DecimalField(decimal_places=1, max_digits=3)),
                ('egg_cycles', models.IntegerField()),
                ('against_normal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_fire', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_water', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_electric', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_grass', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_ice', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_fight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_poison', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_ground', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_flying', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_psychic', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_bug', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_rock', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_ghost', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_dragon', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_dark', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_steel', models.DecimalField(decimal_places=1, max_digits=3)),
                ('against_fairy', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
