# Generated by Django 3.2.8 on 2021-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnlist',
            name='ability_hidden',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='base_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='base_friendship',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='catch_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='egg_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='german_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='growth_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='percentage_male',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnlist',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
