import sqlalchemy as _sql
import database as _database


class Pkmnlist(_database.Base):
    __tablename__ = "pkmnlist_pkmnlist"
    id = _sql.Column(_sql.Integer, primary_key=True, index=True,  autoincrement=True)
    pokedex_number = _sql.Column(_sql.Integer, index=True)
    name = _sql.Column(_sql.String, index=True)
    german_name = _sql.Column(_sql.String, index=True)
    japanese_name = _sql.Column(_sql.String, index=True)
    generation = _sql.Column(_sql.Integer, index=True)
    status = _sql.Column(_sql.String, index=True)
    species = _sql.Column(_sql.String, index=True)
    type_number = _sql.Column(_sql.Integer, index=True)
    type_1 = _sql.Column(_sql.String, index=True)
    type_2 = _sql.Column(_sql.String, index=True)
    height_m = _sql.Column(_sql.DECIMAL, index=True)
    weight_kg = _sql.Column(_sql.DECIMAL, index=True)
    abilities_number = _sql.Column(_sql.Integer, index=True)
    ability_1 = _sql.Column(_sql.String, index=True)
    ability_2 = _sql.Column(_sql.String, index=True)
    ability_hidden = _sql.Column(_sql.String, index=True)
    total_points = _sql.Column(_sql.Integer, index=True)
    hp = _sql.Column(_sql.Integer, index=True)
    attack = _sql.Column(_sql.Integer, index=True)
    defense = _sql.Column(_sql.Integer, index=True)
    sp_attack = _sql.Column(_sql.Integer, index=True)
    sp_defense = _sql.Column(_sql.Integer, index=True)
    speed = _sql.Column(_sql.Integer, index=True)
    catch_rate = _sql.Column(_sql.Integer, index=True)
    base_friendship = _sql.Column(_sql.Integer, index=True)
    base_experience = _sql.Column(_sql.Integer, index=True)
    growth_rate = _sql.Column(_sql.String, index=True)
    egg_type_number = _sql.Column(_sql.Integer, index=True)
    egg_type_1 = _sql.Column(_sql.String, index=True)
    egg_type_2 = _sql.Column(_sql.String, index=True)
    percentage_male = _sql.Column(_sql.DECIMAL, index=True)
    egg_cycles = _sql.Column(_sql.Integer, index=True)
    against_normal = _sql.Column(_sql.DECIMAL, index=True)
    against_fire = _sql.Column(_sql.DECIMAL, index=True)
    against_water = _sql.Column(_sql.DECIMAL, index=True)
    against_electric = _sql.Column(_sql.DECIMAL, index=True)
    against_grass = _sql.Column(_sql.DECIMAL, index=True)
    against_ice = _sql.Column(_sql.DECIMAL, index=True)
    against_fight = _sql.Column(_sql.DECIMAL, index=True)
    against_poison = _sql.Column(_sql.DECIMAL, index=True)
    against_ground = _sql.Column(_sql.DECIMAL, index=True)
    against_flying = _sql.Column(_sql.DECIMAL, index=True)
    against_psychic = _sql.Column(_sql.DECIMAL, index=True)
    against_bug = _sql.Column(_sql.DECIMAL, index=True)
    against_rock = _sql.Column(_sql.DECIMAL, index=True)
    against_ghost = _sql.Column(_sql.DECIMAL, index=True)
    against_dragon = _sql.Column(_sql.DECIMAL, index=True)
    against_dark = _sql.Column(_sql.DECIMAL, index=True)
    against_steel = _sql.Column(_sql.DECIMAL, index=True)
    against_fairy = _sql.Column(_sql.DECIMAL, index=True)
